on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
    paths-ignore:
      - ".github/workflows/server.yaml"
      - "LICENSE"
      - "README.md"
      - "setup-docker.py"
      - "chromedriver.Dockerfile"
      - "server/tests/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build
        run: |
          docker buildx build . -f Dockerfile
